#This module standardizes the workflow to locate earthquake
"""
hypoxpy.workflow
================

This module provides a high-level workflow for improving earthquake locations
and performing relative relocation using external location engines such as
HYPOINVERSE and HYPODD. It operates on user-supplied phase picks and event
catalogs generated by upstream tools (e.g., GAMMA, EQTransformer) and does not
perform phase picking or event association itself.

IMPORTANT DISCLAIMER
--------------------
- Earthquake location and relocation results depend strongly on the quality of
  input phase picks, event catalogs, velocity models, and parameter choices.
- Default workflows and parameter settings reflect common practice but may not
  be appropriate for all datasets or tectonic settings.
- Users are responsible for performing quality control, validating results, and
  understanding the scientific assumptions behind each processing step.
- Direct use of poorly constrained initial locations for relative relocation
  (e.g., skipping absolute location before HYPODD) is discouraged and allowed
  only through explicit user override.

This software is provided as a research tool and is not intended for operational
or hazard-critical use without independent verification.
"""
import os,glob,sys

#
def sanity_check(cfg):
    # -------------------------
    # Logical workflow checks
    # -------------------------
    if cfg["run_hypodd"] and not cfg["run_hypoinverse"]:
        if not cfg["allow_gamma_only"]:
            raise ValueError(
                "Direct GAMMA → HYPODD is discouraged. "
                "Set allow_gamma_only=True to override."
            )

    # -------------------------
    # Required inputs
    # -------------------------
    if cfg["run_hypoinverse"] and cfg["velocity_model"] is None:
        raise ValueError("velocity_model is required for HYPOINVERSE.")

    # -------------------------
    # Parameter consistency
    # -------------------------
    if "fix_depth" in cfg["hypoinv"] and "depth" not in cfg["hypoinv"]:
        raise ValueError(
            "hypoinv.fix_depth=True requires hypoinv.depth to be set."
        )

    # -------------------------
    # Soft warnings (not fatal)
    # -------------------------
    if cfg["run_hypodd"]:
        if cfg["hypodd"].get("min_obs", 0) < 6:
            print(
                "WARNING: HypoDD min_obs < 6 may lead to unstable solutions."
            )

def make_config(velocity_model=None,run_hypoinverse=True,run_hypodd=True,
                allow_gamma_only=False,hypoinv_kwargs=None,hypodd_kwargs=None,
                gamma_kwargs=None):
    """
    Create a validated configuration dictionary for hypoxpy workflows.
    """

    cfg = {
        "velocity_model": velocity_model,
        "run_hypoinverse": run_hypoinverse,
        "run_hypodd": run_hypodd,
        "allow_gamma_only": allow_gamma_only,
        "gamma": gamma_kwargs or {},
        "hypoinv": hypoinv_kwargs or {},
        "hypodd": hypodd_kwargs or {},
    }

    sanity_check(cfg)
    return cfg

def relocate(phase_file,outdir,config=None,cleanup=True):
    """
    End-to-end earthquake relocation workflow.

    NOTE: This function applies recommended defaults but does not replace
    dataset-specific tuning or scientific judgment.
    """
    
    print("Main driver of running the workflow.")
    if config is None:
        config = make_config()

    os.makedirs(outdir, exist_ok=True)

    gamma_cat = utils.gamma_to_catalog(
        phase_file,
        outdir,
        **config["gamma"],
    )

    if config["run_hypoinverse"]:
        hypoinv_cat = HypoInvCore.run(
            gamma_cat,
            config["velocity_model"],
            outdir,
            **config["hypoinv"],
        )
    else:
        hypoinv_cat = gamma_cat

    if config["run_hypodd"]:
        hypodd_cat = HypoDDCore.run(
            hypoinv_cat,
            outdir,
            **config["hypodd"],
        )
    else:
        hypodd_cat = hypoinv_cat

    return {
        "gamma": gamma_cat,
        "hypoinverse": hypoinv_cat if config["run_hypoinverse"] else None,
        "hypodd": hypodd_cat if config["run_hypodd"] else None,
    }

